#!/bin/bash
#
# Usage:
#
#   ./scripts/local-test
#
# Installs a local Drupal site, runs it with `drush runserver`, executes
# the behat tests, and then stops the webserver.
#
SELF_DIRNAME="`dirname -- "$0"`"

../$SELF_DIRNAME/bin/setup-before-tests
(
  cd ../$SELF_DIRNAME/behat; ../$SELF_DIRNAME/bin/behat --config=behat-local.yml
)
../$SELF_DIRNAME/bin/stop-webserver
