#!/bin/bash

# If a --uri= or @alias is needed for Drush calls,
# pass it in as the first (only) parameter to this script.
SITE_IDENTIFIER="$1"

SELF_DIRNAME="`dirname -- "$0"`"
PROJECT_BASE_DIR="`cd -P -- "$SELF_DIRNAME/.." && pwd -P`"
DRUPAL_ROOT="$PROJECT_BASE_DIR/drupal"

cd "$DRUPAL_ROOT"

#
# Install the configuration settings form wk_config
#
#drush "$SITE_IDENTIFIER" cb-umaster MODULENAME -y
